### ISSUE TITLE
WARC revision 1.1 (augmentation): add new named fields for deduplication

### ISSUE THREAD

**Issue by cleymour** [iipc/warc-specifications#10] opened 2015-06-16 14:46 UTC
Definition: the issue has been identified and describe by the IIPC harvesting working, which has proposed a solution:https://iipc.github.io/warc-specifications/specifications/warc-deduplication/recording-arbitrary-duplicates.html.

Decision: the preconisation from the HWG should be written in the standard.

Action: Kristinn Sigurðsson (and al.) to include the preconisation in the standard.

**Comment by saraaubry** [comment] 2015-11-16 15:45
Question from the ISO WG:
In the section "Profile: Server Not Modified", why is only the WARC-Refers-To-Date added and not the WARC-Refers-To-Target-URI?

**Comment by kris-sigur** [comment] 2015-11-16 15:54
@saraaubry Because server-not-modified deduplication can **only** occur on the same URI. Thus `WARC-Refers-To-Target-URI` is redundant in that profile. It would always be the same as `WARC-Target-URI`.

**Comment by saraaubry** [comment] 2015-11-16 15:55
The following changes have been integrated in the revised ISO draft during the ISO working group meeting on November 16-17, 2015 :

After section 5.11, add two new sections:

5.12       WARC-Refers-To-Target-URI

The WARC-Refers-To-Target-URI field contains the WARC-Target-URI of a record for which the present record is considered a revisit of.

WARC-Refers-To-Target-URI     = "WARC-Refers-To-Target-URI" ":" uri

The WARC-Refers-To-Target-URI field may be used to associate a record of type 'revisit' with another record which contains the resource which has not been archived. The WARC-Refers-To-Target-URI shall be used in conjunction with the WARC-Refers-To-Date.

The WARC-Refers-To-Target-URI field shall not be used in 'warcinfo', 'response', 'metadata', 'conversion', ‘resource’, 'request', and 'continuation' records.

5.12       WARC-Refers-To-Date

The WARC-Refers-To-Date field contains the WARC-Date of a record for which the present record is considered a revisit of.

WARC-Refers-To-Date     = "WARC-Refers-To-Date" ":" w3c-iso8601
w3c-iso8601 = <YYYY-MM-DDThh:mm:ssZ>

The WARC-Refers-To-Date field may be used to associate a record of type 'revisit' with another record which contains the resource which has not been archived. The WARC-Refers-To-Date shall be used in conjunction with the WARC-Refers-To-Target-URI.
The WARC-Refers-To-Date field shall not be used in 'warcinfo', 'response', 'metadata', 'conversion', ‘resource’, 'request', and 'continuation' records.

==> need to be added in the examples.

2/ Ok with proposed changes:
 This 'revisit' profile may be used whenever a subsequent consideration
 of a URI provides payload content which a strong digest function, such
-as SHA-1, indicates is identical to a previously recorded version.
+as SHA-1, indicates is identical to a previously recorded version. It
+is not necessary that the URI of the original capture and the revisit
+be identical.

present, it shall be interpreted the same as a 'response' record type
 for the same URI, but truncated to avoid storing the duplicate content.
 A WARC-Truncated header with reason 'length' shall be used for any
-identical-digest truncation.
+identical-digest truncation. It is recommended that server response 
+headers be preserved in the revisit record in this manner.


3/ Two last modifications in the sections 6.7.2 and 6.7.3 should be identical:

Using a WARC-Refers-To header to identify a specific prior record from which the unmodified content can be retrieved is recommended, to minimize the risk of misinterpreting the 'revisit' record. The following two optional fields can also be used to associate the revisit record with the original record. Their use is recommended:
-        WARC-Refers-To-Target-URI. Its value should be equal to the WARC-Target-URI in the WARC record that the current record is considered a duplicate of.
-        WARC-Refers-To-Date. Its value should be equal to the WARC-Date in the WARC record that the current record is considered a duplicate of.

**Comment by saraaubry** [comment] 2015-11-16 16:03
@kris-sigur ok. As a matter of readability and consistency, we would like to recommend to also add the WARC-Refers-To-Target-URI together with the WARC-Refers-To-Date even it's redundant. 
In the fields description, we stated that "The WARC-Refers-To-Target-URI shall be used in conjunction with the WARC-Refers-To-Date." Would that be ok?

**Comment by kris-sigur** [comment] 2015-11-16 16:10
@saraaubry It doesn't break anything but it is, as I said, redundant in the case of *server-not-modified* records.

**Comment by saraaubry** [comment] 2015-11-16 16:41
@kris-sigur we went back to your original proposal and take out the recommendation to use the two fields in conjunction.

**Comment by saraaubry** [comment] 2017-12-07 10:12
Included in WARC 1.1

**Closed by saraaubry** 2017-12-07 10:12 UTC
Labels: warc-format
